services:
  processorapi:
    image: processorapi
    build:
      context: .
      dockerfile: ProcessorApi/Dockerfile
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080

  processorwebui:
    image: processorwebui
    build:
      context: .
      dockerfile: ProcessorWebUI/Dockerfile
    ports:
      - "5004:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ProcessorApiBaseUrl=http://processorapi:8080/
    depends_on:
      - processorapi